- hosts: localhost
  tasks:
  - name: "Install httpd package"
    package:
      name: "httpd"
      state: "present"
      
  - name: "copy page"
    copy:
      src: "index.html"
      dest: "/var/www/html/"

  - name: "start web service"
    service:
      name: "httpd"
      state: "started"

