- hosts: localhost
  tasks:
  - name: "Install httpd package"
    package:
      name: "httpd"
      state: "present"
      
  - name: "copy page"
    copy:
      content: "hii this is from ansible-jenkins"
      dest: "/var/www/html/index.html"

  - name: "start web service"
    service:
      name: "httpd"
      state: "started"

